# Generated by Django 6.1 on 2026-08-21 16:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpverification',
            old_name='attempts',
            new_name='attempt_count',
        ),
        migrations.RenameField(
            model_name='otpverification',
            old_name='otp_code_hash',
            new_name='code_hash',
        ),
        migrations.RenameField(
            model_name='otpverification',
            old_name='is_verified',
            new_name='used',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('EMAIL_VERIFICATION', 'Email Verification'), ('LOGIN', 'Login'), ('PASSWORD_RESET', 'Password Reset'), ('HIGH_RISK_AUTH', 'High Risk Auth')], default='LOGIN', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_photo', models.TextField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
