# Generated by Django 6.1 on 2026-08-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_failed_login_count_user_last_login_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='method',
            field=models.CharField(choices=[('password', 'Password'), ('google_oauth', 'Google OAuth')], default='password', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
