# Generated by Django 6.1 on 2026-08-30 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_loginattempt_method_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='mfa_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64)),
                ('delivery_channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='authenticat_user_id_d1d607_idx')],
            },
        ),
    ]
