# Generated by Django 6.1 on 2026-08-30 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('account_locked', 'Account Locked'), ('account_auto_unlocked', 'Account Auto Unlocked'), ('ip_throttled', 'IP Throttled'), ('suspicious_pattern', 'Suspicious Pattern'), ('manual_unlock', 'Manual Unlock')], max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='authenticat_event_t_a8e92a_idx'), models.Index(fields=['ip_address', '-created_at'], name='authenticat_ip_addr_5302f2_idx'), models.Index(fields=['user', '-created_at'], name='authenticat_user_id_6bfbe5_idx')],
            },
        ),
    ]
