# Generated by Django 6.1 on 2026-08-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_locked_at_user_locked_until_securityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('VOTER', 'Voter'), ('ELECTION_CREATOR', 'Election Creator')], default='VOTER', max_length=20),
        ),
    ]
