# Generated by Django 6.1 on 2026-09-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('EMAIL_VERIFICATION', 'Email Verification'), ('LOGIN', 'Login'), ('PASSWORD_RESET', 'Password Reset'), ('HIGH_RISK_AUTH', 'High Risk Auth'), ('ELECTION_VERIFICATION', 'Election Verification')], max_length=30),
        ),
    ]
