# Generated by Django 5.2.17 on 2026-09-14 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0010_election_organization_election_position_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source_filename', models.CharField(help_text='Matches vector source metadata', max_length=255, unique=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('namespace', models.CharField(default='digivote-docs', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Knowledge Document',
                'verbose_name_plural': 'AI Knowledge Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAssistantFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(db_index=True)),
                ('rating', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assistant_feedbacks', to='elections.election')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assistant_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Assistant Feedback',
                'verbose_name_plural': 'AI Assistant Feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_assistan_user_id_80bac4_idx'), models.Index(fields=['rating', 'created_at'], name='ai_assistan_rating_d0c9ce_idx'), models.Index(fields=['request_id'], name='ai_assistan_request_943a18_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUnansweredQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='Redacted user question text.')),
                ('normalized_question', models.TextField(db_index=True, help_text='Canonical normalized question text for aggregation.')),
                ('reason', models.CharField(choices=[('NO_RAG_CONTEXT', 'No RAG Context'), ('LOW_RELEVANCE', 'Low Relevance'), ('UNSUPPORTED_REQUEST', 'Unsupported Request'), ('AI_ERROR', 'AI Error')], default='NO_RAG_CONTEXT', max_length=50)),
                ('intent', models.CharField(default='WEBSITE_HELP', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], db_index=True, default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_unanswered_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Unanswered Question',
                'verbose_name_plural': 'AI Unanswered Questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ai_assistan_status_d0052a_idx'), models.Index(fields=['reason'], name='ai_assistan_reason_698e5f_idx')],
            },
        ),
    ]
