// Mock Elections covering all 6 lifecycle statuses + edge cases
export const initialElections = [
  {
    id: 'elec-act-1',
    title: 'National Parliamentary General Election 2026',
    description: 'Sovereign parliamentary legislative contest conducted across certified citizen rolls.',
    election_type: 'general',
    status: 'active',
    is_locked: true,
    start_datetime: '2026-09-01T08:00:00Z',
    end_datetime: '2026-09-30T18:00:00Z',
    actual_start_at: '2026-09-01T08:00:00Z',
    require_email_otp: true,
    require_webcam_verification: false,
    require_biometric_verification: false,
    results_visibility: 'manual',
    results_visible_at: null,
    allow_vote_change: false,
    created_at: '2026-08-15T10:00:00Z',
    total_eligible_voters: 120,
    voters_participated: 78,
    already_voted: false
  },
  {
    id: 'elec-sch-2',
    title: 'State Legislative Assembly By-Election 2026',
    description: 'Statutory legislative by-election for vacant parliamentary constituency seats.',
    election_type: 'general',
    status: 'scheduled',
    is_locked: true,
    start_datetime: '2026-10-15T09:00:00Z',
    end_datetime: '2026-10-16T17:00:00Z',
    actual_start_at: null,
    require_email_otp: true,
    require_webcam_verification: false,
    require_biometric_verification: false,
    results_visibility: 'immediate',
    results_visible_at: null,
    allow_vote_change: false,
    created_at: '2026-08-20T11:30:00Z',
    total_eligible_voters: 85,
    voters_participated: 0,
    already_voted: false
  },
  {
    id: 'elec-cfg-3',
    title: 'Municipal Council Leadership Election',
    description: 'Civic municipal administrative body council member and mayor elections.',
    election_type: 'organizational',
    status: 'configured',
    is_locked: false,
    start_datetime: null,
    end_datetime: null,
    actual_start_at: null,
    require_email_otp: true,
    require_webcam_verification: false,
    require_biometric_verification: false,
    results_visibility: 'manual',
    results_visible_at: null,
    allow_vote_change: false,
    created_at: '2026-08-25T14:00:00Z',
    total_eligible_voters: 45,
    voters_participated: 0,
    already_voted: false
  },
  {
    id: 'elec-drf-4',
    title: 'Constitutional Policy Advisory Referendum',
    description: 'Direct citizen consultative referendum on regional environmental policy amendments.',
    election_type: 'referendum',
    status: 'draft',
    is_locked: false,
    start_datetime: null,
    end_datetime: null,
    actual_start_at: null,
    require_email_otp: true,
    require_webcam_verification: false,
    require_biometric_verification: false,
    results_visibility: 'manual',
    results_visible_at: null,
    allow_vote_change: false,
    created_at: '2026-09-02T09:15:00Z',
    total_eligible_voters: 0,
    voters_participated: 0,
    already_voted: false
  },
  {
    id: 'elec-cmp-5',
    title: 'Federation Officers Presidential Ballot 2025',
    description: 'Certified biennial national union leadership and board of trustees election.',
    election_type: 'organizational',
    status: 'completed',
    is_locked: true,
    start_datetime: '2025-11-01T08:00:00Z',
    end_datetime: '2025-11-03T18:00:00Z',
    actual_start_at: '2025-11-01T08:00:00Z',
    stopped_at: null,
    require_email_otp: true,
    require_webcam_verification: false,
    require_biometric_verification: false,
    results_visibility: 'manual',
    results_visible_at: null,
    is_published: true,
    allow_vote_change: false,
    created_at: '2025-10-10T12:00:00Z',
    total_eligible_voters: 150,
    voters_participated: 138,
    already_voted: true
  },
  {
    id: 'elec-can-6',
    title: 'Metropolitan Transit Advisory Ballot (Emergency Abort)',
    description: 'City metropolitan transit consultative measure aborted under administrative observation.',
    election_type: 'poll',
    status: 'cancelled',
    is_locked: true,
    start_datetime: '2026-08-01T08:00:00Z',
    end_datetime: '2026-08-05T18:00:00Z',
    actual_start_at: '2026-08-01T08:00:00Z',
    stopped_at: '2026-08-02T11:45:00Z',
    stop_reason: 'Unforeseen infrastructure emergency caused network disruption in District 4. Terminated per election protocol.',
    require_email_otp: true,
    require_webcam_verification: false,
    require_biometric_verification: false,
    results_visibility: 'manual',
    results_visible_at: null,
    allow_vote_change: false,
    created_at: '2026-07-20T10:00:00Z',
    total_eligible_voters: 60,
    voters_participated: 14,
    already_voted: false
  },
  // Edge Case 1: Webcam / Biometric Requirement Flag Enabled (Triggers Voter Blocked State)
  {
    id: 'elec-edge-webcam',
    title: 'High-Security Judicial Bar Council Election 2026',
    description: 'Special constituency election configured with advanced hardware identity requirements.',
    election_type: 'organizational',
    status: 'active',
    is_locked: true,
    start_datetime: '2026-09-01T08:00:00Z',
    end_datetime: '2026-09-30T18:00:00Z',
    actual_start_at: '2026-09-01T08:00:00Z',
    require_email_otp: true,
    require_webcam_verification: true,
    require_biometric_verification: true,
    results_visibility: 'manual',
    results_visible_at: null,
    allow_vote_change: false,
    created_at: '2026-08-18T10:00:00Z',
    total_eligible_voters: 30,
    voters_participated: 5,
    already_voted: false
  },
  // Edge Case 2: Small Electorate (<10 ballots) with Published Results
  {
    id: 'elec-edge-small',
    title: 'Executive Committee Special Resolution Ballot',
    description: 'Small leadership committee ballot (<10 voters) demonstrating privacy disclaimer.',
    election_type: 'organizational',
    status: 'completed',
    is_locked: true,
    start_datetime: '2026-08-10T08:00:00Z',
    end_datetime: '2026-08-11T18:00:00Z',
    actual_start_at: '2026-08-10T08:00:00Z',
    require_email_otp: true,
    require_webcam_verification: false,
    require_biometric_verification: false,
    results_visibility: 'immediate',
    results_visible_at: null,
    is_published: true,
    allow_vote_change: false,
    created_at: '2026-08-01T09:00:00Z',
    total_eligible_voters: 9,
    voters_participated: 8,
    already_voted: true
  },
  // Edge Case 3: Tied Contest
  {
    id: 'elec-edge-tie',
    title: 'Public Utility Oversight Council Poll',
    description: 'Citizen opinion poll with exact parity between top candidates demonstrating tie handling.',
    election_type: 'poll',
    status: 'completed',
    is_locked: true,
    start_datetime: '2026-08-05T08:00:00Z',
    end_datetime: '2026-08-07T18:00:00Z',
    actual_start_at: '2026-08-05T08:00:00Z',
    require_email_otp: true,
    require_webcam_verification: false,
    require_biometric_verification: false,
    results_visibility: 'manual',
    results_visible_at: null,
    is_published: true,
    allow_vote_change: false,
    created_at: '2026-07-28T14:00:00Z',
    total_eligible_voters: 50,
    voters_participated: 40,
    already_voted: true
  }
];
