# Generated by Django 6.1 on 2026-08-21 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('elections', '0002_remove_vote_candidate_remove_vote_constituency_and_more'),
        ('locations', '0001_initial'),
        ('voters', '0003_remove_voter_constituency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='candidates.candidate')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='locations.constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='VoteTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_transactions', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='VoteReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='elections.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='voters.voterprofile')),
            ],
            options={
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
