# Generated by Django 6.1 on 2026-09-06 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_alter_electionauditlog_action'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_choice', models.BinaryField()),
                ('submitted_at', models.DateTimeField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_ballots', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionEncryptionKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_key', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_key', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('total_ballots_cast', models.PositiveIntegerField(default=0)),
                ('integrity_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='election_result', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='BallotConfirmationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_tokens', to='elections.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_tokens', to='elections.eligiblevoter')),
            ],
            options={
                'indexes': [models.Index(fields=['token_hash'], name='voting_ball_token_h_fd38c4_idx'), models.Index(fields=['election', 'voter'], name='voting_ball_electio_3a67e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_results', to='elections.candidate')),
                ('election_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_results', to='voting.electionresult')),
            ],
            options={
                'ordering': ['-vote_count'],
                'unique_together': {('election_result', 'candidate')},
            },
        ),
    ]
