# Generated by Django 6.1 on 2026-09-07 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_candidate_is_active_and_more'),
        ('voting', '0002_ballot_electionencryptionkey_electionresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed', models.BooleanField(default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_authorizations', to='elections.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_authorizations', to='elections.eligiblevoter')),
            ],
            options={
                'indexes': [models.Index(fields=['token_hash'], name='voting_voti_token_h_021d51_idx'), models.Index(fields=['election', 'voter'], name='voting_voti_electio_2191c4_idx')],
            },
        ),
    ]
