# Generated by Django 6.1 on 2026-08-17 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='VoterIDCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voter_id_cards', to='voters.constituency')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter_id_card', to='voters.voter')),
            ],
        ),
    ]
