# Generated by Django 6.1 on 2026-08-21 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_vote_candidate_remove_vote_constituency_and_more'),
        ('locations', '0001_initial'),
        ('voters', '0002_voter_date_of_birth_voter_gender_voteridcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='constituency',
        ),
        migrations.AlterField(
            model_name='voteridcard',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voter_id_cards', to='locations.constituency'),
        ),
        migrations.RemoveField(
            model_name='voter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='verified_by',
        ),
        migrations.CreateModel(
            name='VoterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('voter_reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('verification_method', models.CharField(blank=True, choices=[('VOTER_ID', 'Voter ID Verification'), ('AADHAAR', 'Aadhaar Verification'), ('DIGILOCKER', 'DigiLocker Verification'), ('MANUAL', 'Manual Admin Verification')], max_length=20, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('face_photo_url', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='locations.constituency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_voters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='voteridcard',
            name='voter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter_id_card', to='voters.voterprofile'),
        ),
        migrations.DeleteModel(
            name='Constituency',
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
