# Generated by Django 6.1 on 2026-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_remove_voter_constituency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterprofile',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual Admin Verification'), ('EMAIL_OTP', 'Email OTP Verification')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='VoterIDCard',
        ),
    ]
