# Generated by Django 6.1 on 2026-08-21 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
        migrations.AlterUniqueTogether(
            name='votereceipt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='votereceipt',
            name='election',
        ),
        migrations.RemoveField(
            model_name='votereceipt',
            name='voter',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='end_date',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='start_date',
            new_name='start_datetime',
        ),
        migrations.AddField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('GENERAL', 'General Election'), ('BY_ELECTION', 'By-Election'), ('MUNICIPAL', 'Municipal Election')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=15),
        ),
        migrations.CreateModel(
            name='ElectionPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='elections.election')),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='VoteReceipt',
        ),
    ]
