# Generated by Django 6.1 on 2026-08-31 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_vote_candidate_remove_vote_constituency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='election',
            name='name',
        ),
        migrations.AddField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='election',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='title',
            field=models.CharField(default='Untitled ElectionUntitled Election', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('general', 'General'), ('organizational', 'Organizational'), ('poll', 'Poll'), ('referendum', 'Referendum')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='election',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
