# Generated by Django 6.1 on 2026-08-31 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_created_by(apps, schema_editor):
    Election = apps.get_model('elections', 'Election')
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    
    # Fetch default admin/superuser or first user
    default_user = User.objects.filter(is_superuser=True).first() or User.objects.first()
    if not default_user:
        # Create fallback user if none exists
        default_user = User.objects.create(
            username='admin_fallback',
            email='admin_fallback@digivote.gov',
            role='ADMIN',
            is_staff=True,
            is_superuser=True
        )
    
    Election.objects.filter(created_by__isnull=True).update(created_by=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_election_options_remove_election_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_created_by, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('party_or_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/%Y/%m/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
            ],
            options={
                'ordering': ['display_order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibleVoter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('has_voted', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_voters', to='elections.election')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligible_elections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('election', 'email')},
            },
        ),
    ]
