# Generated by Django 6.1 on 2026-08-31 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_alter_election_created_by_candidate_eligiblevoter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionRules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('results_visibility', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('results_visible_at', models.DateTimeField(blank=True, null=True)),
                ('allow_vote_change', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionVerificationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('require_email_otp', models.BooleanField(default=True)),
                ('require_webcam_verification', models.BooleanField(default=False)),
                ('require_biometric_verification', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_config', to='elections.election')),
            ],
        ),
    ]
