# Generated by Django 6.1 on 2026-09-05 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_electionrules_electionverificationconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='actual_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='stop_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='stopped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stopped_elections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ElectionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('voter_added', 'Voter Added'), ('voter_removed', 'Voter Removed'), ('candidate_added', 'Candidate Added'), ('candidate_updated', 'Candidate Updated'), ('candidate_removed', 'Candidate Removed'), ('verification_config_changed', 'Verification Config Changed'), ('rules_changed', 'Rules Changed'), ('status_changed', 'Status Changed'), ('started', 'Started'), ('stopped', 'Stopped'), ('auto_transitioned', 'Auto Transitioned')], max_length=40)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='elections.election')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
