# Generated by Django 6.1 on 2026-09-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_election_actual_start_at_election_stop_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('voter_added', 'Voter Added'), ('voter_removed', 'Voter Removed'), ('candidate_added', 'Candidate Added'), ('candidate_updated', 'Candidate Updated'), ('candidate_removed', 'Candidate Removed'), ('verification_config_changed', 'Verification Config Changed'), ('rules_changed', 'Rules Changed'), ('status_changed', 'Status Changed'), ('started', 'Started'), ('stopped', 'Stopped'), ('auto_transitioned', 'Auto Transitioned'), ('tally_integrity_mismatch', 'Tally Integrity Mismatch'), ('results_published', 'Results Published')], max_length=40),
        ),
    ]
