# Generated by Django 6.1 on 2026-09-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_alter_electionauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('general', 'General Election'), ('academic', 'Academic / Student Council'), ('club', 'Club / Society'), ('workplace', 'Workplace / Committee'), ('poll', 'Internal Poll'), ('organizational', 'Organizational'), ('referendum', 'Referendum')], default='general', max_length=30),
        ),
    ]
