# Generated by Django 6.1 on 2026-09-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_alter_election_election_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eligiblevoter',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('OTP_VERIFIED', 'OTP Verified'), ('FACE_VERIFIED', 'Face Verified'), ('VERIFIED', 'Fully Verified')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='eligiblevoter',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligiblevoter',
            name='voted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='electionauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('voter_added', 'Voter Added'), ('voter_removed', 'Voter Removed'), ('candidate_added', 'Candidate Added'), ('candidate_updated', 'Candidate Updated'), ('candidate_removed', 'Candidate Removed'), ('verification_config_changed', 'Verification Config Changed'), ('rules_changed', 'Rules Changed'), ('status_changed', 'Status Changed'), ('started', 'Started'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('auto_transitioned', 'Auto Transitioned'), ('tally_integrity_mismatch', 'Tally Integrity Mismatch'), ('results_published', 'Results Published'), ('results_unpublished', 'Results Unpublished'), ('verification_completed', 'Verification Completed'), ('vote_submitted', 'Vote Submitted')], max_length=40),
        ),
    ]
