# Generated by Django 6.1 on 2026-09-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0009_candidate_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='position_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eligiblevoter',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eligiblevoter',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eligiblevoter',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
